### ISSUE TITLE
Returns not owned property's rule

### ISSUE THREAD

**Issue by onca-vega** [tecnocen-com/yii2-formgenerator#11]
When I send GET to `field/field_id/rule/rule_id/property`, always return the properties, even if the rule_id isn't representing a rule owned by the field with field_id.

**Comment by Faryshta** [comment]
Which version of yii2-formgenerator is it using? I can't replicate this issue with latest release.

**Comment by neverabe** [comment]
@onca-vega, can you confirm in the latest release.
