### ISSUE TITLE
Proposal for dependent sections and sectionFields

### ISSUE THREAD

**Issue by onca-vega** [tecnocen-com/yii2-formgenerator#13]
I was thinking a way to solve the issue related to dependency between sections and fields, in other words, how you can show or hide some fields or sections acording some certain field value or another section.

Watching the database structure, this idea runs over two tables:
* formgenerator_form_section (table A)
* formgenerator_form_section_field (table B)

Also, thinking about what are the initial values to understand what element is hidding or showing another one, we have:
* dependent_section_id
* dependent_field_id
* dependent_value
* dependent_relation

This initial values could apply both to a section or a field, so they should be able to be registered on every table A and table B row. I don't know if the best way is saving it into a JSON in just 1 new column, or adding 4 columns, one per initial value.

Let's describe some examples:

1) **Field dependent of field**
In this case, we assume that we have a form with 2 sections:
* First section (with ID 1) has a boolean field (with ID 2) named "Show the field of my second section"
* Second section (with ID 3) has a string field (with ID 4) named "I'm showed!"

So, the goal is when I set TRUE the "Show the field of my second section" field on first section, the "I'm showed!" field on second section should appear, meanwhile is setted to FALSE, second section field should hide, right?

For that we should add in the table B row for "I'm showed!" field 4 different data, the same listed above:
* dependent_section_id: 1
* dependent_field_id: 2
* dependent_value: TRUE
* dependent_relation: ==

This will tell the "I'm showed!" field to be showed only when the field with id 2, in the section with id 1, is equal (==) to TRUE.

2) **Section dependent of field**
In this case, we assume that we have a form with 2 sections:
* First section (with ID 1) has a boolean field (with ID 2) named "Show the second section"
* Second section (with ID 3)

So, the goal is when I set TRUE the "Show the second section" field on first section, the second section should appear, meanwhile is setted to FALSE, second section should hide.

For that we should add in the table A row for second section 4 different data, the same listed above:
* dependent_section_id: 1
* dependent_field_id: 2
* dependent_value: TRUE
* dependent_relation: ==

This will tell the second section to be showed only when the field with id 2, in the section with id 1, is equal (==) to TRUE.

3) **Field dependent of section**
In this case, we assume that we have a form with 2 sections:
* First section (with ID 1)
* Second section (with ID 2) has a string field (with ID 3) named "I'm showed!"

So, the goal is when I show the first section, the "I'm showed!" field on second section should appear, meanwhile it is hidden, second section field should hide, right?

For that we should add in the table B row for "I'm showed!" field 4 different data, the same listed above:
* dependent_section_id = 1
* dependent_field_id = null
* dependent_value = null
* dependent_relation = null

This will tell the "I'm showed!" field to be showed only when the section with id 1, is shown.

4) **Section dependent of section**
In this case, we assume that we have a form with 2 sections:
* First section (with ID 1)
* Second section (with ID 2)

So, the goal is when I show the first section, the second section should appear, meanwhile it is hidden, second section should hide.

For that we should add in the table A row for second section 4 different data, the same listed above:
* dependent_section_id = 1
* dependent_field_id = null
* dependent_value = null
* dependent_relation = null

This will tell the second section to be showed only when the section with id 1, is shown.

**Comment by Faryshta** [comment]
how would you manage nested conditions or boolean algebra?

for example show a section named "Cohabitant" when "status = 'married' || (status = 'cohabitation' && relation_time > 3years)"

and how would you manage derivate information? for example lets say I have a field "birthdate" and I want to show a section only when the birthdate is 18 years ago or older? how about only showing certain section on the person birthday?

**Comment by onca-vega** [comment]
You are right, this idea only supports direct information and one condition per row.

**Comment by Faryshta** [comment]
would that suffice?

**Comment by Faryshta** [comment]
Closing this issue since it doesnt solve the requirement.
