### ISSUE TITLE
Client requests sequence speed improvement

### ISSUE THREAD

**Issue by onca-vega** [tecnocen-com/yii2-formgenerator#2]
Hello, as we commented two weeks ago, I need to get data-type, all propertys and rules of a field in expand mode, in order to improve client requests speed.

Thanks.

**Comment by Faryshta** [comment]
currently there is no official support for nested expand, but I can provide routes like this

- `fg1/field{/id}?expand=data-type` gets all fields and data type
- `fg1/field/<field_id>/rule{/id}?expand=properties` get all rules for a field with properties

**Comment by onca-vega** [comment]
First route is good, but in second route, with 'properties' you mean both rules and propertys? 
If it's like that so it's better than actual mode.

**Comment by Faryshta** [comment]
yes, i updated the comment.

The second gets all rules with properties.

once there is nested support we will be able to

`fg1/field{/id}?expand=data-type,rule.properties` in one call.

**Comment by onca-vega** [comment]
So it's ok that way, thanks, i'll be pending on these changes.
