### ISSUE TITLE
Bug founded about parentAttribute variable

### ISSUE THREAD

**Issue by onca-vega** [tecnocen-com/yii2-formgenerator#3]
Hi, I found a mistake on new positioning release: https://alquimia3.adelantoad.com/index.php/api/v1/form/1/section?accessToken=211b998748a759e74930aa561a0770ccf36b29c6&per-page=100

I'll be pending on fixment of this bug. Thanks.

**Comment by Faryshta** [comment]
fixed in https://github.com/tecnocen-com/yii2-formgenerator/commit/092fe928fcd6d40fb1c0dd6b996fb74f5e283757
