### ISSUE TITLE
Fields Grouped as components

### ISSUE THREAD

**Issue by onca-vega** [tecnocen-com/yii2-formgenerator#6]
Hi!! I need a way to define components, so this components exists as a group of defined fields, I mean for example: 

In the case of "servicios postales" service, where it's component is formed by the "codigo postal", "colonia", "municipio", "estado" and "buscar colonia manualmente" fields.

So this component should have a name, and a way to connect to it's determined fields, and there must be a way to know if a field belongs to a determined component or it's just an independent field.

**Comment by Faryshta** [comment]
this is outside the capacities of the form generator since the form generator has no control over external services or how they handle information.
